### ISSUE TITLE
Building fails because of duplicate classes on Android / Kotlin 1.6.0

### ISSUE THREAD

**Issue by skaldebane** [f-nyx/kotlin-search#1]
Hi! I have an Android project where I use this library, but it seems like the lucene-analyzers-common and lucene-snowball modules have some classes repeated (as far as I understand) which Gradle only likes so much.

('jetified-*' prefix is added because of the Android Jetifier, which makes libraries made for higher Java versions work on lower versions, and doesn't change anything about classes or functionality of libraries)

```
Duplicate class org.apache.lucene.analysis.snowball.SnowballFilter found in modules jetified-lucene-analyzers-common-8.4.1 (org.apache.lucene:lucene-analyzers-common:8.4.1) and jetified-lucene-snowball-3.0.3 (org.apache.lucene:lucene-snowball:3.0.3)
Duplicate class org.tartarus.snowball.Among found in modules jetified-lucene-analyzers-common-8.4.1 (org.apache.lucene:lucene-analyzers-common:8.4.1) and jetified-lucene-snowball-3.0.3 (org.apache.lucene:lucene-snowball:3.0.3)
Duplicate class org.tartarus.snowball.SnowballProgram found in modules jetified-lucene-analyzers-common-8.4.1 (org.apache.lucene:lucene-analyzers-common:8.4.1) and jetified-lucene-snowball-3.0.3 (org.apache.lucene:lucene-snowball:3.0.3)
Duplicate class org.tartarus.snowball.ext.DanishStemmer found in modules jetified-lucene-analyzers-common-8.4.1 (org.apache.lucene:lucene-analyzers-common:8.4.1) and jetified-lucene-snowball-3.0.3 (org.apache.lucene:lucene-snowball:3.0.3)
Duplicate class org.tartarus.snowball.ext.DutchStemmer found in modules jetified-lucene-analyzers-common-8.4.1 (org.apache.lucene:lucene-analyzers-common:8.4.1) and jetified-lucene-snowball-3.0.3 (org.apache.lucene:lucene-snowball:3.0.3)
Duplicate class org.tartarus.snowball.ext.EnglishStemmer found in modules jetified-lucene-analyzers-common-8.4.1 (org.apache.lucene:lucene-analyzers-common:8.4.1) and jetified-lucene-snowball-3.0.3 (org.apache.lucene:lucene-snowball:3.0.3)
Duplicate class org.tartarus.snowball.ext.FinnishStemmer found in modules jetified-lucene-analyzers-common-8.4.1 (org.apache.lucene:lucene-analyzers-common:8.4.1) and jetified-lucene-snowball-3.0.3 (org.apache.lucene:lucene-snowball:3.0.3)
Duplicate class org.tartarus.snowball.ext.FrenchStemmer found in modules jetified-lucene-analyzers-common-8.4.1 (org.apache.lucene:lucene-analyzers-common:8.4.1) and jetified-lucene-snowball-3.0.3 (org.apache.lucene:lucene-snowball:3.0.3)
Duplicate class org.tartarus.snowball.ext.German2Stemmer found in modules jetified-lucene-analyzers-common-8.4.1 (org.apache.lucene:lucene-analyzers-common:8.4.1) and jetified-lucene-snowball-3.0.3 (org.apache.lucene:lucene-snowball:3.0.3)
Duplicate class org.tartarus.snowball.ext.GermanStemmer found in modules jetified-lucene-analyzers-common-8.4.1 (org.apache.lucene:lucene-analyzers-common:8.4.1) and jetified-lucene-snowball-3.0.3 (org.apache.lucene:lucene-snowball:3.0.3)
Duplicate class org.tartarus.snowball.ext.HungarianStemmer found in modules jetified-lucene-analyzers-common-8.4.1 (org.apache.lucene:lucene-analyzers-common:8.4.1) and jetified-lucene-snowball-3.0.3 (org.apache.lucene:lucene-snowball:3.0.3)
Duplicate class org.tartarus.snowball.ext.ItalianStemmer found in modules jetified-lucene-analyzers-common-8.4.1 (org.apache.lucene:lucene-analyzers-common:8.4.1) and jetified-lucene-snowball-3.0.3 (org.apache.lucene:lucene-snowball:3.0.3)
Duplicate class org.tartarus.snowball.ext.KpStemmer found in modules jetified-lucene-analyzers-common-8.4.1 (org.apache.lucene:lucene-analyzers-common:8.4.1) and jetified-lucene-snowball-3.0.3 (org.apache.lucene:lucene-snowball:3.0.3)
Duplicate class org.tartarus.snowball.ext.LovinsStemmer found in modules jetified-lucene-analyzers-common-8.4.1 (org.apache.lucene:lucene-analyzers-common:8.4.1) and jetified-lucene-snowball-3.0.3 (org.apache.lucene:lucene-snowball:3.0.3)
Duplicate class org.tartarus.snowball.ext.NorwegianStemmer found in modules jetified-lucene-analyzers-common-8.4.1 (org.apache.lucene:lucene-analyzers-common:8.4.1) and jetified-lucene-snowball-3.0.3 (org.apache.lucene:lucene-snowball:3.0.3)
Duplicate class org.tartarus.snowball.ext.PorterStemmer found in modules jetified-lucene-analyzers-common-8.4.1 (org.apache.lucene:lucene-analyzers-common:8.4.1) and jetified-lucene-snowball-3.0.3 (org.apache.lucene:lucene-snowball:3.0.3)
Duplicate class org.tartarus.snowball.ext.PortugueseStemmer found in modules jetified-lucene-analyzers-common-8.4.1 (org.apache.lucene:lucene-analyzers-common:8.4.1) and jetified-lucene-snowball-3.0.3 (org.apache.lucene:lucene-snowball:3.0.3)
Duplicate class org.tartarus.snowball.ext.RomanianStemmer found in modules jetified-lucene-analyzers-common-8.4.1 (org.apache.lucene:lucene-analyzers-common:8.4.1) and jetified-lucene-snowball-3.0.3 (org.apache.lucene:lucene-snowball:3.0.3)
Duplicate class org.tartarus.snowball.ext.RussianStemmer found in modules jetified-lucene-analyzers-common-8.4.1 (org.apache.lucene:lucene-analyzers-common:8.4.1) and jetified-lucene-snowball-3.0.3 (org.apache.lucene:lucene-snowball:3.0.3)
Duplicate class org.tartarus.snowball.ext.SpanishStemmer found in modules jetified-lucene-analyzers-common-8.4.1 (org.apache.lucene:lucene-analyzers-common:8.4.1) and jetified-lucene-snowball-3.0.3 (org.apache.lucene:lucene-snowball:3.0.3)
Duplicate class org.tartarus.snowball.ext.SwedishStemmer found in modules jetified-lucene-analyzers-common-8.4.1 (org.apache.lucene:lucene-analyzers-common:8.4.1) and jetified-lucene-snowball-3.0.3 (org.apache.lucene:lucene-snowball:3.0.3)
Duplicate class org.tartarus.snowball.ext.TurkishStemmer found in modules jetified-lucene-analyzers-common-8.4.1 (org.apache.lucene:lucene-analyzers-common:8.4.1) and jetified-lucene-snowball-3.0.3 (org.apache.lucene:lucene-snowball:3.0.3)
```

**Comment by f-nyx** [comment]
It seems you have a dependency called `jetified-lucene-analyzers-common` that has conflicts with the lucene's dependencies. Where this dependency comes from?

btw: I'll upgrade the project to support kotlin 1.6 and lucene 9

**Comment by skaldebane** [comment]
Thanks for your response! I edited my question with more details.

I also think I've found a workaround for this (by excluding the 'lucene-snowball' module in Gradle) but I have yet to try if that works.

And I'm also looking forward to the new version! I initially thought this project was dead 2 years ago, but I really love the DSL and how easy it is to get started. There's still room for improvement, but this is pretty darn good! Keep it up 😄

**Comment by f-nyx** [comment]
I use this project to add search support for some other projects, so I try to keep it working, thanks for reporting the issue!

It seems `lucene-snowball` is now deprecated, the stemmers were moved to `lucene-analysis-common`.

I already updated Lucene and Kotlin, the new version 1.1.0 is available in maven central, it should fix your issue.

**Comment by skaldebane** [comment]
Thanks! That was quick⚡👌🏻 I'll try it out now.

**Comment by skaldebane** [comment]
Hi again! 

After trying out the 1.1.0 update, now there are no build errors, and the app builds successfully. However, it crashes the app immediately after launch.

Here's how I use it in the code:
```kotlin
class BookReaderApp : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        // some code
        val indexManager = IndexManager(indexPath = File(filesDir, "search-index").path) // CRASH!
        // more code...
    }
}
```

Note that `filesDir` is just a private app storage folder (`File` instance) exposed by Android, to which I have read/write access.
However, this crashes this app with this stacktrace:

```
W/izardofoz.debu: Accessing hidden method Ljava/lang/invoke/MethodHandles;->byteArrayViewVarHandle(Ljava/lang/Class;Ljava/nio/ByteOrder;)Ljava/lang/invoke/VarHandle; (greylist-max-o, linking, denied)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bperiod.bookreader.thewonderfulwizardofoz.debug, PID: 20424
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bperiod.bookreader.thewonderfulwizardofoz.debug/com.bperiod.bookreader.BookReaderApp}: java.lang.reflect.InvocationTargetException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3792)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Constructor.call(CallerImpl.kt:41)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at be.rlab.search.AnalyzerFactory.newAnalyzer(AnalyzerFactory.kt:97)
        at be.rlab.search.IndexManager.<init>(IndexManager.kt:55)
        at com.bperiod.bookreader.BookReaderApp.onCreate(BookReaderApp.kt:27)
        at android.app.Activity.performCreate(Activity.java:8198)
        at android.app.Activity.performCreate(Activity.java:8182)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8512) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
     Caused by: java.lang.NoSuchMethodError: No static method byteArrayViewVarHandle(Ljava/lang/Class;Ljava/nio/ByteOrder;)Ljava/lang/invoke/VarHandle; in class Ljava/lang/invoke/MethodHandles; or its super classes (declaration of 'java.lang.invoke.MethodHandles' appears in /apex/com.android.art/javalib/core-oj.jar)
        at org.apache.lucene.util.BitUtil.<clinit>(BitUtil.java:38)
        at org.apache.lucene.util.StringHelper.murmurhash3_x86_32(StringHelper.java:167)
        at org.apache.lucene.util.BytesRefHash.doHash(BytesRefHash.java:425)
        at org.apache.lucene.util.BytesRefHash.findHash(BytesRefHash.java:313)
        at org.apache.lucene.util.BytesRefHash.add(BytesRefHash.java:250)
        at org.apache.lucene.analysis.miscellaneous.StemmerOverrideFilter$Builder.add(StemmerOverrideFilter.java:197)
        at org.apache.lucene.analysis.nl.DutchAnalyzer.<init>(DutchAnalyzer.java:131)
        at org.apache.lucene.analysis.nl.DutchAnalyzer.<init>(DutchAnalyzer.java:108)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Constructor.call(CallerImpl.kt:41) 
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108) 
        at be.rlab.search.AnalyzerFactory.newAnalyzer(AnalyzerFactory.kt:97) 
        at be.rlab.search.IndexManager.<init>(IndexManager.kt:55) 
        at com.bperiod.bookreader.BookReaderApp.onCreate(BookReaderApp.kt:27) 
        at android.app.Activity.performCreate(Activity.java:8198) 
        at android.app.Activity.performCreate(Activity.java:8182) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8512) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
```

Notice that the first line of the stacktrace is just Android logging a detected usage of reflection, for a function which is included later in the stacktrace (`byteArrayViewVarHandle(...)` in `java.lang.invoke.MethodHandles`), causing the crash because it wasn't found.

I think this is an Android-only issue (never tried it any other way, just speculating).
I'm open to providing more details.

And please forgive my late response, I've been busy with studies recently and forgot to report this for a while.

**Comment by skaldebane** [comment]
After some searching about Lucene itself, it seems that it uses some JDK 17-only APIs which are not available in Android (max supported version in Android is Java 11).

However, it's still kind of weird that it builds successfully nevertheless. Probably it's using all of these APIs through reflection?

**Comment by f-nyx** [comment]
`java.lang.invoke.MethodHandles.byteArrayViewVarHandle` was introduced in Java 9, and Lucene 9 runs on JDK 11.

It seems you have a problem with one of your dependencies, if you look at the error it says:

`declaration of 'java.lang.invoke.MethodHandles' appears in /apex/com.android.art/javalib/core-oj.jar`

For some reason `core-oj` overwrites the JVM class `java.lang.invoke.MethodHandles`. Maybe this dependency embeds some specific JDK packages?

I don't know what package manager do you use, but you should be able to generate the dependency tree and check why `core-oj` generates this conflict. With maven, you can run `mvn dependency:tree`.

**Comment by skaldebane** [comment]
Aha, now I get it. I've misread the readme of this repository [lukhnos/mobilelucene](https://github.com/lukhnos/mobilelucene) where he talks about Lucene using JDK 1.7-only APIs, like NIO.2.

As for the `core-oj.jar`, I'm not sure what it exactly does, but what I know is that Android uses a custom runtime library that, while it has a good chunk of Java's APIs, doesn't have a few of them like java.swing because it's not needed.

I use Gradle, which is the default for Android projects.

**Comment by skaldebane** [comment]
Here's the `MethodHandles` reference in Oracle's JDK: [MethodHandles | Java SE 9 & JDK 9](https://docs.oracle.com/javase/9/docs/api/java/lang/invoke/MethodHandles.html)
And here it is on Android: [MethodHandles | Android Developers](https://developer.android.com/reference/java/lang/invoke/MethodHandles)

The Android one misses so many methods, including the `byteArrayViewVarHandle` method.

While Lucene uses it here: [apache/lucene -> BitUtil.java](https://github.com/apache/lucene/blob/c57d6e5f8c8a8cae943f99ba7393550579666eb4/lucene/core/src/java/org/apache/lucene/util/BitUtil.java)

Plus the existence of such ports shows clearly that there's a problem with Lucene on Android, so this issue is related to Lucene, and is not your library's fault.

**Comment by skaldebane** [comment]
From the `BitUtil.java` last commit, it seems like this is added only recently in Lucene 9: https://github.com/apache/lucene/commit/c57d6e5f8c8a8cae943f99ba7393550579666eb4

Would adding an older version of Lucene manually to the Gradle configuration work here?

**Comment by skaldebane** [comment]
Android 13 seems to have brought proper VarHandle support: [Runtime and compiler support for `java.lang.invoke.VarHandle`](https://developer.android.com/about/versions/13/features#:~:text=Runtime%20and%20compiler%20support%20for%20java.lang.invoke.VarHandle).
Now that function shows up in the docs: [`byteArrayViewVarHandle`](https://developer.android.com/about/versions/13/features#:~:text=an%20array%20type-,byteArrayViewVarHandle,-Added%20in%20Android)

Although this is only for Android 13 (and 12) for now, I guess it's going to be possible to desugar it soon, so that it works on older APIs.

**Comment by skaldebane** [comment]
This issue has been stale for quite some time now, and as we've discussed this is a problem with Android support for functions used by Lucene, and not with your library, so it is out of scope for this project. Closing it now.
However, I still found this to be pretty helpful on some desktop apps where it works fine. Thanks a lot for the amazing library!
